---
title: "Fund"
author: "Jiaqi Sun"
date: "2022-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(dplyr)
library(tidytext)
library(topicmodels)
library(tidyverse)
library(tm)
```

```{r}
fund <- read_xlsx("Fund_Strategy_Data.xlsx", col_names = TRUE)

fund %>% 
  mutate(fund_number = row_number()) -> fund
fund
```

```{r}
data(stop_words)
stop_words <- bind_rows(tibble(word = c("br"), lexicon = c("custom")), stop_words)

fund_words <- fund %>% 
  unnest_tokens(word, FUND_STRATEGY) %>%
  anti_join(stop_words) %>% 
  count(fund_number, word, sort = TRUE)

fund_words
```

```{r}
fund_tf_idf <- fund_words %>%
  bind_tf_idf(word, fund_number, n) %>% 
  arrange(idf, tf_idf)

fund_tf_idf
```
```{r}
uni_words <- unique(fund_tf_idf$word)
# .5% level
boundary1 <- length(uni_words) * .005
customized_stop_words1 <- as.tibble(uni_words[1:boundary1])
customized_stop_words1

# 1% level
boundary2 <- length(uni_words) * .01
customized_stop_words2 <- as.tibble(uni_words[1:boundary2])
customized_stop_words2

# 1.5% level
boundary3 <- length(uni_words) * .015
customized_stop_words3 <- as.tibble(uni_words[1:boundary3])
customized_stop_words3
```

<!-- n-grams -->
<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tidytext) -->

<!-- fund_bigrams <- fund %>% -->
<!--   unnest_tokens(bigram, fund_number, token = "ngrams", n = 2) %>% -->
<!--   filter(!is.na(bigram)) %>%  -->
<!--   select(fund_number, bigram) -->

<!-- fund_bigrams -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fund_bigrams %>% -->
<!--   count(bigram, sort = TRUE) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- library(tidyr) -->

<!-- bigrams_separated <- fund_bigrams %>% -->
<!--   separate(bigram, c("word1", "word2"), sep = " ") -->

<!-- bigrams_filtered <- bigrams_separated %>% -->
<!--   filter(!word1 %in% customized_stop_words$word) %>% -->
<!--   filter(!word2 %in% customized_stop_words$word) -->

<!-- # new bigram counts: -->
<!-- bigram_counts <- bigrams_filtered %>%  -->
<!--   count(word1, word2, sort = TRUE) -->

<!-- bigram_counts -->
<!-- ``` -->

<!-- ```{r} -->
<!-- bigrams_united <- bigrams_filtered %>% -->
<!--   unite(bigram, word1, word2, sep = " ") -->

<!-- bigrams_united -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fund %>% -->
<!--   unnest_tokens(trigram, FUND_STRATEGY, token = "ngrams", n = 3) %>% -->
<!--   filter(!is.na(trigram)) %>% -->
<!--   separate(trigram, c("word1", "word2", "word3"), sep = " ") %>% -->
<!--   filter(!word1 %in% customized_stop_words$word, -->
<!--          !word2 %in% customized_stop_words$word, -->
<!--          !word3 %in% customized_stop_words$word) %>% -->
<!--   count(word1, word2, word3, sort = TRUE) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- bigrams_filtered %>% -->
<!--   filter(word2 == "companies") %>% -->
<!--   count(INVESTMENT_TYPE, word1, sort = TRUE) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tidytext) -->

<!-- fund_bigrams <- fund %>% -->
<!--   unnest_tokens(bigram, FUND_STRATEGY, token = "ngrams", n = 2) %>% -->
<!--   filter(!is.na(bigram)) %>%  -->
<!--   select(INVESTMENT_TYPE, bigram) -->

<!-- fund_bigrams -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fund_dtm <- fund_words%>% -->
<!--   cast_dtm(INVESTMENT_TYPE, word, n) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # set a seed so that the output of the model is predictable -->
<!-- fund_lda <- LDA(fund_dtm, k = 6, control = list(seed = 1234)) -->
<!-- fund_lda -->
<!-- #> A LDA_VEM topic model with 6 topics. -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fund_topics <- tidy(fund_lda, matrix = "beta") -->
<!-- fund_topics -->
<!-- ``` -->

<!-- ```{r} -->
<!-- top_terms <- fund_topics %>% -->
<!--   group_by(topic) %>% -->
<!--   slice_max(beta, n = 5) %>%  -->
<!--   ungroup() %>% -->
<!--   arrange(topic, -beta) -->

<!-- top_terms -->
<!-- ``` -->

